### ISSUE TITLE
So guys, we did it.

### ISSUE THREAD

**Issue by kairusds** [MindfulMinun/discord-haruka#2]
So guys, we did it, we reached a quarter of a million subscribers, 250,000 subscribers and still growing the fact that we've reached this number in such a short amount of time is just phenomenal, I'm-I'm just amazed. Thank you all so much for supporting this channel and helping it grow. I-I love you guys... You guys are just awesome. So as you can really tell, this isn't really a montage parody. This is more of a kind of thank you/update kind of video. So for this video, I'll just quickly go over two things: Firstly, advertisements. And more importantly, the future of this channel, and what kind of direction it's headed. Okay, so firstly with the advertisements. Believe it or not, but Montage Parodies are actually a copyright minefield. New content is being claimed by companies everyday. We could use something from.. Let's say five years ago. And tomorrow a huge company could come along and claim their product as theirs, and we have no control over that. Meaning that any video we use their product in could either get copyright striked, or lose monetization. Meaning that all of the money made off that video.. Would get sent to the company, and not us. The only real way to counter this is to get advertisements placed on my channel. I mean, it's a win win for everyone ya know.

**Comment by kairusds** [comment]
@MindfulMinun senpai noticed me

**Comment by TheTimgor** [comment]
jesus fuck, benji

**Comment by MindfulMinun** [comment]
smh
